### ISSUE TITLE
java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by iamayden** [jaminchanks/AnnotationProcess-Demo#1]
Demo运行报错，通过反射找不到相关类。
```
java.lang.NoSuchMethodException: com.rhythm7.annotationprocessordemo.MainActivity.<init> [class com.rhythm7.annotationprocessordemo.MainActivity]
        at java.lang.Class.getConstructor0(Class.java:2328)
        at java.lang.Class.getConstructor(Class.java:1725)
        at com.rhythm7.lib_api.RandomUtil.inject(RandomUtil.java:27)
        at com.rhythm7.annotationprocessordemo.MainActivity.onCreate(MainActivity.java:23)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
```

**Comment by jaminchanks** [comment]
@20170911 已升级至gradle 5，我这边没有问题了，你试试。。。
